name: Parameterized Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: development
jobs:
  input-parameter:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploy the application to ${{ inputs.environment }}
        
        
 
